version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-local
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - NODE_ENV=development
      - GENERIC_TIMEZONE=Australia/Sydney
      - TZ=Australia/Sydney
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_files:/files

volumes:
  n8n_data:
