name: UpBank Sync Monitor

on:
  schedule:
    # Run every 6 hours to monitor sync health
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Monitor Sync Health
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Monitor UpBank sync health and identify any issues:

            1. Check the sync_state_tracking table in Supabase
            2. Identify the last successful sync timestamp
            3. Check for any sync gaps (missing date ranges in the last 7 days)
            4. Look for failed transactions or retry attempts
            5. Verify no duplicate transactions were created
            6. Check ML categorization stats (how many auto-categorized vs manual review needed)

            If issues found:
            - Report detailed gap analysis
            - Suggest recovery actions
            - Flag if manual intervention needed

            Provide a health report with:
            - Last sync: [timestamp]
            - Sync gaps: [list of date ranges]
            - Failed syncs: [count and details]
            - Overall health: [HEALTHY/WARNING/CRITICAL]
        env:
          UPBANK_API_TOKEN: ${{ secrets.UPBANK_API_TOKEN }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_URL: https://gshsshaodoyttdxippwx.supabase.co
          SUPABASE_PROJECT_ID: gshsshaodoyttdxippwx

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ UpBank Sync Health Issue Detected',
              body: 'The UpBank sync monitor detected issues. Check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.',
              labels: ['automation', 'urgent']
            })
