name: Manual UpBank Sync

on:
  workflow_dispatch:
    inputs:
      sync_type:
        description: 'Sync type'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - accounts
          - categories
          - transactions
      days:
        description: 'Days to sync (for full/transaction sync)'
        required: false
        default: '30'
        type: string
      account_id:
        description: 'Specific account ID (for transaction sync only)'
        required: false
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Manual Sync
        run: |
          if [ "${{ inputs.sync_type }}" = "full" ]; then
            node scripts/sync-upbank-data.js full ${{ inputs.days }}
          elif [ "${{ inputs.sync_type }}" = "transactions" ] && [ -n "${{ inputs.account_id }}" ]; then
            node scripts/sync-upbank-data.js transactions ${{ inputs.account_id }} ${{ inputs.days }}
          else
            node scripts/sync-upbank-data.js ${{ inputs.sync_type }}
          fi
        env:
          UPBANK_API_TOKEN: ${{ secrets.UPBANK_API_TOKEN }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_URL: https://gshsshaodoyttdxippwx.supabase.co

      - name: Upload Sync Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sync-logs-${{ github.run_number }}
          path: |
            *.log
          retention-days: 30
          if-no-files-found: ignore
