name: Daily UpBank Sync

on:
  schedule:
    # Run at 10 PM UTC (8 AM Sydney time next day)
    - cron: '0 22 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run UpBank Sync
        uses: anthropics/anthropic-quickstarts/claude-code-action@main
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Execute the daily UpBank sync for recent transactions:

            1. Run the sync-upbank command for recent transactions (last 24 hours)
            2. Verify the sync completed successfully
            3. Check for any errors or unusual transactions
            4. If there are sync gaps, identify the missing date ranges
            5. Provide a summary of:
               - Number of transactions synced
               - Any errors encountered
               - Business expenses detected (Mokai/MOK HOUSE)
               - Sync health status

            Use the /sync-upbank command with 'recent' parameter.
        env:
          UPBANK_API_TOKEN: ${{ secrets.UPBANK_API_TOKEN }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_URL: https://gshsshaodoyttdxippwx.supabase.co
          SUPABASE_PROJECT_ID: gshsshaodoyttdxippwx

      - name: Report Results
        if: always()
        run: |
          echo "Daily UpBank sync completed"
          echo "Check workflow logs for detailed sync summary"
