name: Manual UpBank Sync

on:
  workflow_dispatch:
    inputs:
      sync_type:
        description: 'Sync type'
        required: true
        default: 'recent'
        type: choice
        options:
          - recent
          - full
          - check
      days:
        description: 'Days to sync (for full sync)'
        required: false
        default: '30'
      force_recategorize:
        description: 'Force ML recategorization of existing transactions'
        required: false
        type: boolean
        default: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Manual UpBank Sync
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Execute manual UpBank sync with the following parameters:

            Sync Type: ${{ inputs.sync_type }}
            Days: ${{ inputs.days }}
            Force Recategorize: ${{ inputs.force_recategorize }}

            Instructions:
            1. If sync_type is 'recent': Sync last 24 hours of transactions
            2. If sync_type is 'full': Sync last ${{ inputs.days }} days
            3. If sync_type is 'check': Only verify sync health, don't sync new data

            4. If force_recategorize is true:
               - Re-run ML categorization on all transactions from the sync period
               - Update categories based on latest ML model predictions
               - Report recategorization changes

            5. Provide detailed summary:
               - Transactions synced: [count]
               - New transactions: [count]
               - Updated transactions: [count]
               - Business expenses detected: [count and total amount]
               - ML categorization stats: [auto/review/manual counts]
               - Any errors or warnings

            Use the /sync-upbank command with appropriate parameters.
        env:
          UPBANK_API_TOKEN: ${{ secrets.UPBANK_API_TOKEN }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_URL: https://gshsshaodoyttdxippwx.supabase.co
          SUPABASE_PROJECT_ID: gshsshaodoyttdxippwx

      - name: Upload Sync Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sync-report-${{ github.run_number }}
          path: |
            *.log
            reports/*.json
          retention-days: 30
