name: Daily UpBank Sync

on:
  schedule:
    # Run at 10 PM UTC (8 AM Sydney time next day)
    - cron: '0 22 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run UpBank Sync
        run: node scripts/sync-upbank-data.js full 7
        env:
          UPBANK_API_TOKEN: ${{ secrets.UPBANK_API_TOKEN }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_URL: https://gshsshaodoyttdxippwx.supabase.co

      - name: Sync Summary
        if: always()
        run: |
          echo "✅ Daily UpBank sync completed"
          echo "📅 Synced last 7 days of transactions"
          echo "Check logs above for detailed results"
